#############################################################################
# Makefile for building: Wholesale.app/Contents/MacOS/Wholesale
# Generated by qmake (3.1) (Qt 5.13.0)
# Project:  Wholesale.pro
# Template: app
# Command: /Applications/qtfolder/5.13.0/clang_64/bin/qmake -o Makefile Wholesale.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/Applications/qtfolder/5.13.0/clang_64/lib/QtWidgets.framework/Headers -I/Applications/qtfolder/5.13.0/clang_64/lib/QtGui.framework/Headers -I/Applications/qtfolder/5.13.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/qtfolder/5.13.0/clang_64/mkspecs/macx-clang -F/Applications/qtfolder/5.13.0/clang_64/lib
QMAKE         = /Applications/qtfolder/5.13.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Applications/qtfolder/5.13.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Applications/qtfolder/5.13.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Wholesale1.0.0
DISTDIR = /Users/peternguyen/Developer/CS8/Wholesale/Wholesale/.tmp/Wholesale1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Applications/qtfolder/5.13.0/clang_64/lib
LIBS          = $(SUBLIBS) -F/Applications/qtfolder/5.13.0/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = date.cpp \
		history.cpp \
		item.cpp \
		list.cpp \
		main.cpp \
		mainwindow.cpp \
		members.cpp \
		warehouse.cpp moc_mainwindow.cpp
OBJECTS       = date.o \
		history.o \
		item.o \
		list.o \
		main.o \
		mainwindow.o \
		members.o \
		warehouse.o \
		moc_mainwindow.o
DIST          = day1.txt \
		day2.txt \
		day3.txt \
		day4.txt \
		day5.txt \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/qdevice.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/device_config.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/unix.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/mac.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/macx.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/sanitize.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/clang.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/qconfig.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/qt_config.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/spec_post.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/toolchain.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/toolchain.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/default_pre.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/default_post.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/mac.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/warn_on.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/qt.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/resources.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/moc.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/uic.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/qmake_use.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/file_copies.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/exceptions.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/yacc.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/lex.prf \
		Wholesale.pro date.h \
		history.h \
		item.h \
		linked_list_functions.h \
		list.h \
		mainwindow.h \
		members.h \
		node.h \
		warehouse.h date.cpp \
		history.cpp \
		item.cpp \
		list.cpp \
		main.cpp \
		mainwindow.cpp \
		members.cpp \
		warehouse.cpp
QMAKE_TARGET  = Wholesale
DESTDIR       = 
TARGET        = Wholesale.app/Contents/MacOS/Wholesale

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.13
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/peternguyen/Developer/CS8/Wholesale/Wholesale/Wholesale.pro


include /Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Wholesale.app/Contents/MacOS/Wholesale: ui_mainwindow.h $(OBJECTS)  
	@test -d Wholesale.app/Contents/MacOS/ || mkdir -p Wholesale.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Wholesale.pro /Applications/qtfolder/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf /Applications/qtfolder/5.13.0/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/qdevice.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/device_config.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/unix.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/mac.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/macx.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/sanitize.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/clang.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/qconfig.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/qt_config.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/spec_post.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/toolchain.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/toolchain.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/default_pre.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/default_post.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/mac.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/warn_on.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/qt.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/resources.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/moc.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/uic.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/qmake_use.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/file_copies.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/exceptions.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/yacc.prf \
		/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/lex.prf \
		Wholesale.pro \
		/Applications/qtfolder/5.13.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/qtfolder/5.13.0/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/qtfolder/5.13.0/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Wholesale.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/spec_pre.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/qdevice.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/device_config.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/unix.conf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/mac.conf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/macx.conf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/sanitize.conf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/gcc-base.conf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/clang.conf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/common/clang-mac.conf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/qconfig.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_location.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/qt_functions.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/qt_config.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/spec_post.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/toolchain.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/toolchain.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/default_pre.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/resolve_config.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/default_post.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/qml_debug.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/mac.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/warn_on.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/qt.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/resources.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/moc.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/uic.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/unix/thread.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/qmake_use.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/file_copies.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/rez.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/exceptions.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/yacc.prf:
/Applications/qtfolder/5.13.0/clang_64/mkspecs/features/lex.prf:
Wholesale.pro:
/Applications/qtfolder/5.13.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/qtfolder/5.13.0/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/qtfolder/5.13.0/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Wholesale.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

Wholesale.app/Contents/PkgInfo: 
	@test -d Wholesale.app/Contents || mkdir -p Wholesale.app/Contents
	@$(DEL_FILE) Wholesale.app/Contents/PkgInfo
	@echo "APPL????" > Wholesale.app/Contents/PkgInfo
Wholesale.app/Contents/Resources/empty.lproj: 
	@test -d Wholesale.app/Contents/Resources || mkdir -p Wholesale.app/Contents/Resources
	@touch Wholesale.app/Contents/Resources/empty.lproj
	
Wholesale.app/Contents/Info.plist: 
	@test -d Wholesale.app/Contents || mkdir -p Wholesale.app/Contents
	@$(DEL_FILE) Wholesale.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Wholesale,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.Wholesale,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Wholesale,g" -e "s,@LIBRARY@,Wholesale,g" -e "s,\$${EXECUTABLE_NAME},Wholesale,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /Applications/qtfolder/5.13.0/clang_64/mkspecs/macx-clang/Info.plist.app >Wholesale.app/Contents/Info.plist

all: Makefile \
		Wholesale.app/Contents/PkgInfo \
		Wholesale.app/Contents/Resources/empty.lproj \
		Wholesale.app/Contents/Info.plist Wholesale.app/Contents/MacOS/Wholesale

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Applications/qtfolder/5.13.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents date.h history.h item.h linked_list_functions.h list.h mainwindow.h members.h node.h warehouse.h $(DISTDIR)/
	$(COPY_FILE) --parents date.cpp history.cpp item.cpp list.cpp main.cpp mainwindow.cpp members.cpp warehouse.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Wholesale.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode $(EXPORT__PRO_FILE_)

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Applications/qtfolder/5.13.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h /Applications/qtfolder/5.13.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		/Applications/qtfolder/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/qtfolder/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		warehouse.h \
		members.h \
		date.h \
		history.h \
		item.h \
		list.h \
		linked_list_functions.h \
		moc_predefs.h \
		/Applications/qtfolder/5.13.0/clang_64/bin/moc
	/Applications/qtfolder/5.13.0/clang_64/bin/moc $(DEFINES) --include /Users/peternguyen/Developer/CS8/Wholesale/Wholesale/moc_predefs.h -I/Applications/qtfolder/5.13.0/clang_64/mkspecs/macx-clang -I/Users/peternguyen/Developer/CS8/Wholesale/Wholesale -I/Applications/qtfolder/5.13.0/clang_64/lib/QtWidgets.framework/Headers -I/Applications/qtfolder/5.13.0/clang_64/lib/QtGui.framework/Headers -I/Applications/qtfolder/5.13.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Applications/qtfolder/5.13.0/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/Applications/qtfolder/5.13.0/clang_64/bin/uic
	/Applications/qtfolder/5.13.0/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

date.o: date.cpp date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o date.o date.cpp

history.o: history.cpp history.h \
		item.h \
		date.h \
		list.h \
		linked_list_functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o history.o history.cpp

item.o: item.cpp item.h \
		date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o item.o item.cpp

list.o: list.cpp list.h \
		item.h \
		date.h \
		linked_list_functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o list.o list.cpp

main.o: main.cpp mainwindow.h \
		/Applications/qtfolder/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/qtfolder/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		warehouse.h \
		members.h \
		date.h \
		history.h \
		item.h \
		list.h \
		linked_list_functions.h \
		/Applications/qtfolder/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Applications/qtfolder/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Applications/qtfolder/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/qtfolder/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		warehouse.h \
		members.h \
		date.h \
		history.h \
		item.h \
		list.h \
		linked_list_functions.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

members.o: members.cpp members.h \
		date.h \
		history.h \
		item.h \
		list.h \
		linked_list_functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o members.o members.cpp

warehouse.o: warehouse.cpp warehouse.h \
		members.h \
		date.h \
		history.h \
		item.h \
		list.h \
		linked_list_functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o warehouse.o warehouse.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Wholesale/bin || mkdir -p $(INSTALL_ROOT)/opt/Wholesale/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Wholesale/bin/Wholesale.app
	
	-$(QINSTALL) Wholesale.app $(INSTALL_ROOT)/opt/Wholesale/bin/Wholesale.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Wholesale/bin/Wholesale.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Wholesale/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

